export const TRIVIA_TOPICS = [
  // Tech-related (12 topics)
  { label: 'Computer Science', category: 18, difficulty: 'any', tech: true },
  { label: 'Software Programming', category: 18, difficulty: 'hard', tech: true },
  { label: 'Web Development', category: 18, difficulty: 'medium', tech: true },
  { label: 'Tech Gadgets', category: 30, difficulty: 'any', tech: true },
  { label: 'Future Technology', category: 30, difficulty: 'hard', tech: true },
  { label: 'Mathematics', category: 19, difficulty: 'any', tech: true },
  { label: 'Theoretical Physics', category: 17, difficulty: 'hard', tech: true },
  { label: 'Science & Nature', category: 17, difficulty: 'any', tech: true },
  { label: 'Space Exploration', category: 17, difficulty: 'medium', tech: true },
  { label: 'Cybersecurity', category: 18, difficulty: 'hard', tech: true },
  { label: 'Artificial Intelligence', category: 18, difficulty: 'medium', tech: true },
  { label: 'Mobile Tech', category: 30, difficulty: 'medium', tech: true },

  // General & Entertainment (38 topics)
  { label: 'General Knowledge', category: 9, difficulty: 'any' },
  { label: 'GK: Expert Mode', category: 9, difficulty: 'hard' },
  { label: 'Movies & Cinema', category: 11, difficulty: 'any' },
  { label: 'Hollywood Trivia', category: 11, difficulty: 'medium' },
  { label: 'Action Movies', category: 11, difficulty: 'hard' },
  { label: 'TV Shows', category: 14, difficulty: 'any' },
  { label: 'Reality TV', category: 14, difficulty: 'medium' },
  { label: 'Music Trivia', category: 12, difficulty: 'any' },
  { label: 'Classic Rock', category: 12, difficulty: 'hard' },
  { label: 'Pop Icons', category: 12, difficulty: 'medium' },
  { label: 'Video Games', category: 15, difficulty: 'any' },
  { label: 'RPG & Strategy', category: 15, difficulty: 'hard' },
  { label: 'Retro Gaming', category: 15, difficulty: 'medium' },
  { label: 'Board Games', category: 16, difficulty: 'any' },
  { label: 'Animals & Wildlife', category: 27, difficulty: 'any' },
  // History & Geography (Expanded)
  { label: 'Ancient History', category: 23, difficulty: 'any' },
  { label: 'Medieval History', category: 23, difficulty: 'medium' },
  { label: 'Modern World History', category: 23, difficulty: 'any' },
  { label: 'World Wars & Conflicts', category: 23, difficulty: 'hard' },
  { label: 'Indian History', category: 23, difficulty: 'any' },
  { label: 'European Travel', category: 22, difficulty: 'medium' },
  { label: 'American Landmarks', category: 22, difficulty: 'hard' },
  { label: 'Indian Geography', category: 22, difficulty: 'any' },
  { label: 'World Geography', category: 22, difficulty: 'any' },
  
  // Region Specific: India (Mapping to closest OpenTDB categories)
  { label: 'India: General Knowledge', category: 9, difficulty: 'any' },
  { label: 'India: Politics & Civics', category: 24, difficulty: 'any' },
  { label: 'India: Mythology & Culture', category: 20, difficulty: 'any' },
  { label: 'India: Sports & Cricket', category: 21, difficulty: 'any' },

  // General & Entertainment (Rest)
  { label: 'General Knowledge', category: 9, difficulty: 'any' },
  { label: 'GK: Expert Mode', category: 9, difficulty: 'hard' },
  { label: 'Movies & Cinema', category: 11, difficulty: 'any' },
  { label: 'Hollywood Trivia', category: 11, difficulty: 'medium' },
  { label: 'Action Movies', category: 11, difficulty: 'hard' },
  { label: 'TV Shows', category: 14, difficulty: 'any' },
  { label: 'Reality TV', category: 14, difficulty: 'medium' },
  { label: 'Music Trivia', category: 12, difficulty: 'any' },
  { label: 'Classic Rock', category: 12, difficulty: 'hard' },
  { label: 'Pop Icons', category: 12, difficulty: 'medium' },
  { label: 'Video Games', category: 15, difficulty: 'any' },
  { label: 'RPG & Strategy', category: 15, difficulty: 'hard' },
  { label: 'Retro Gaming', category: 15, difficulty: 'medium' },
  { label: 'Board Games', category: 16, difficulty: 'any' },
  { label: 'Animals & Wildlife', category: 27, difficulty: 'any' },
  { label: 'Mythology: Greek & Roman', category: 20, difficulty: 'any' },
  { label: 'Mythical Creatures', category: 20, difficulty: 'medium' },
  { label: 'Sports: All-Star', category: 21, difficulty: 'any' },
  { label: 'Football / Soccer', category: 21, difficulty: 'medium' },
  { label: 'Basketball Trivia', category: 21, difficulty: 'hard' },
  { label: 'Politics & World Affairs', category: 24, difficulty: 'any' },
  { label: 'Art & Artists', category: 25, difficulty: 'any' },
  { label: 'Renaissance Art', category: 25, difficulty: 'hard' },
  { label: 'Celebrities', category: 26, difficulty: 'any' },
  { label: 'Vehicles & Engines', category: 28, difficulty: 'any' },
  { label: 'Automotive Design', category: 28, difficulty: 'hard' },
  { label: 'Comic Books', category: 29, difficulty: 'any' },
  { label: 'Marvel & DC', category: 29, difficulty: 'hard' },
  { label: 'Anime & Manga', category: 31, difficulty: 'any' },
  { label: '90s Anime', category: 31, difficulty: 'medium' },
  { label: 'Cartoons', category: 32, difficulty: 'any' },
  { label: 'Disney Classics', category: 32, difficulty: 'medium' },
  { label: 'Books & Literature', category: 10, difficulty: 'any' },
  { label: 'Classic Novels', category: 10, difficulty: 'hard' },
  { label: 'Modern Bestsellers', category: 10, difficulty: 'medium' },
  { label: 'Theater & Broadway', category: 13, difficulty: 'any' },
];
