export const RACER_SENTENCES = [
  "In a land far away, beyond the mist-covered mountains, there lived a young boy who dreamt of stars. Every night, while his village slept, he would climb the highest peak to catch a glimpse of the celestial bodies dancing in the sky. He believed that each star was a window to another world, a place where magic was real and anything was possible.",
  "The old library was a place of silence and dust, filled with books that hadn't been touched in decades. Its shelves groaned under the weight of ancient knowledge, and the air smelled of aged parchment and forgotten secrets. Elara, a curious researcher, spent her days wandering through the labyrinthine aisles, searching for a map she believed was hidden within the archives.",
  "Deep beneath the ocean waves, where the sunlight never reaches, resides a kingdom of bioluminescent wonders. Corals of every imaginable color glow in the dark, and sea creatures with translucent bodies glide through the water like ghosts. The inhabitants of this underwater realm are masters of light and shadows, using their unique abilities to communicate.",
  "The rapid development of artificial intelligence has fundamentally transformed the way we interact with technology and with each other. From automated systems that can predict our next words to complex algorithms that generate entire worlds from simple prompts, the boundary between human creativity and machine logic is becoming increasingly blurred.",
  "Across the vast expanse of the interstellar void, a lonely research vessel continued its silent mission to map the furthest reaches of our galaxy. Millions of stars blinked in the velvet blackness, each representing a potential world with its own unique history and ecosystem. The crew found comfort in the steady rhythm of their scientific instruments.",
  "The dense forest was alive with the sound of unseen creatures and the rustle of leaves in the wind. Sunlight filtered through the thick canopy in patches, illuminating the vibrant moss that covered the ground like a soft green carpet. Deep within this wilderness, a Hidden Sanctuary stood undisturbed by the passage of centuries.",
  "In the heart of the bustling city, where the skyscrapers touched the clouds, a small clockmaker worked tirelessly on his latest invention. He was obsessed with the idea of capturing time itself and putting it in a jar. Every gear and spring was carefully placed with precision, as he sought to unlock the greatest mystery of the universe.",
  "The desert was a harsh and unforgiving landscape, where the shifting sands could swallow a traveler whole in a matter of minutes. Despite the extreme heat and lack of water, a nomadic tribe had flourished here for generations, living in harmony with the environment and respecting the ancient spirits that guarded the dunes.",
  "High above the clouds, on a floating island made of crystal and light, the Sky People built their cities using the power of the wind. They were masters of flight, soaring through the air on the wings of giant birds that were as large as small planes. Their culture was one of peace and harmony, dedicated to the preservation of the natural world.",
  "The ancient castle stood on the edge of a jagged cliff, overlooking the stormy sea below. Its walls were weathered by time and the elements, yet they remained strong and imposing. Legends spoke of a lost treasure hidden somewhere within its dark and winding corridors, guarded by a phantom knight who would never rest.",
  "In the futuristic metropolis of Neo-Tokyo, the streets were filled with neon lights and holographic advertisements that promised a better life. Hovercars zipped through the air, and robots served as domestic assistants in every household. Yet behind the technological marvels, a secret resistance was forming to challenge the oppressive corporate regime.",
  "The mountain range was a formidable barrier, with peaks that were permanently covered in ice and snow. Only the bravest explorers dared to attempt the climb, facing freezing temperatures and thinning air in their quest for glory. For those who reached the summit, the view was truly breathtaking, revealing the world spread out like a map.",
  "The small village of Willow Creek was a peaceful community, where everyone knew their neighbors and the pace of life was slow and deliberate. The town was famous for its annual harvest festival, where locals gathered to celebrate the bounty of the land and share stories around a large communal bonfire under the harvest moon.",
  "In the laboratory of Dr. Aris Thorne, a revolutionary experiment was about to take place. He had discovered a way to bridge the gap between dimensions, allowing for instantaneous travel across vast distances. As he activated the machine, the air began to hum with energy, and a portal of shimmering light opened up in the center of the room.",
  "The steam-powered train chugged along the tracks, puffing out clouds of white smoke into the crisp morning air. Passengers inside the vintage carriages looked out the windows at the rolling hills and picturesque countryside that passed by. It was a journey back in time, to an era of elegance and discovery on the open rails.",
  "A mystical fog rolled in from the sea, blanketing the coastal town in a thick layer of mystery. The sound of foghorns echoed through the dampened streets, and the lighthouse beam cut through the gloom like a lone sword of light. In the shadows, strange occurrences began to happen, as if the fog had brought something with it.",
  "The underground cavern was a world of stalactites and stalagmites, glowing with the soft light of phosphorescent mushrooms that grew on the damp walls. A clear subterranean river flowed through the center of the cave, its cool waters home to rare and exotic fish that had never seen the light of day on the surface.",
  "In the kingdom of Eldoria, knights and sorcerers worked together to protect the realm from the forces of darkness. Great dragons soared through the skies, and magical artifacts were commonplace in everyday life. The capital city was a marvel of architecture and enchantment, with spires that glowed like embers at nightfall.",
  "The old lighthouse keeper lived a solitary life, dedicated to ensuring that ships safely navigated the treacherous rocks near the shore. He found solace in the constant rhythm of the waves and the vastness of the ocean, feeling a deep connection to the elements that most people could never truly understand or appreciate.",
  "As the final sun began to set on the horizon, the creatures of the night started to emerge from their hiding places. The air was filled with the sounds of nocturnal life, as owls hooted and crickets chirped in a symphony of sound. It was a time of transformation and mystery, where the ordinary world became something extraordinary."
];

export function getRandomSentence(): string {
  return RACER_SENTENCES[Math.floor(Math.random() * RACER_SENTENCES.length)];
}
